# Generated by Django 4.2 on 2023-06-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=50)),
                (
                    "website",
                    models.CharField(default="website", max_length=50),
                ),  # noqa: E501
                ("phone", models.CharField(default="phone", max_length=20)),
                ("email", models.CharField(default="email", max_length=30)),
<<<<<<< HEAD
                (
                    "industry",
                    models.CharField(default="industry", max_length=100),
                ),  # noqa: E501
=======
 add-customer-notes
                ("industry", models.CharField(default="industry", max_length=100)),  # noqa: E501

                ("industry", models.CharField(default="industry", max_length=100)), 
 main
>>>>>>> e8cf1ec4192d573438920d53e1ced77d7572286c
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=75)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("postcode", models.CharField(max_length=10)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("add_note", models.CharField(max_length=100)),
                (
                    "Customer_notes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.customer",
                    ),
                ),
            ],
        ),
    ]
