# Generated by Django 4.1.9 on 2023-06-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_note_delete_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.customer",
            ),
        ),
    ]
