# Generated by Django 4.2 on 2023-07-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_note_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="website.company",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="website.customer",
            ),
        ),
    ]
