# Generated by Django 4.1.9 on 2023-08-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_note_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("1", "New"),
                            ("2", "Open"),
                            ("3", "In progress"),
                            ("4", "Open deal"),
                            ("5", "Unqualified"),
                            ("6", "Attempted to contact"),
                            ("7", "Connected"),
                            ("8", "Bad timing"),
                            ("9", "Unassigned"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="website.customer",
                    ),
                ),
            ],
        ),
    ]
