# Generated by Django 4.1.9 on 2023-08-08 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_rename_contactstatus_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="website.customer",
            ),
        ),
    ]
