# Generated by Django 4.1.9 on 2023-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_customer_lead_status_alter_contact_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("New", "NEW"),
                    ("Open", "OPEN"),
                    ("In Progress", "IN_PROGRESS"),
                    ("Open deal", "OPEN_DEAL"),
                    ("Unqualified", "UNQUALIFIED"),
                    ("Attempted to contact", "ATTEMPTED_TO_CONTACT"),
                    ("Connected", "CONNECTED"),
                    ("Bad Timing", "BAD_TIMING"),
                    ("Unassigned", "UNASSIGNED"),
                ],
                max_length=100,
            ),
        ),
    ]
