# Generated by Django 4.1.9 on 2023-08-09 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_alter_contact_lead_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="lead_status",
            new_name="lead_status_field",
        ),
    ]
