# Generated by Django 4.1.9 on 2023-08-09 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_rename_lead_status_contact_lead_status_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="lead_status",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
