# Generated by Django 4.1.9 on 2023-08-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_customer_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Open", "Open"),
                    ("In Progress", "In progress"),
                    ("Open deal", "Open deal"),
                    ("Unqualified", "Unqualified"),
                    ("Attempted to contact", "Attempted to contact"),
                    ("Connected", "Connected"),
                    ("Bad Timing", "Bad timing"),
                    ("Unassigned", "Unassigned"),
                ],
                default="Unassigned",
                max_length=50,
            ),
        ),
    ]
